FROM tomcat:6.0.53-jre8
RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install maven -y &&  wget -P /opt/"https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz"
WORKDIR /opt
RUN tar xvf apache-maven-*.tar.gz -C /opt
WORKDIR /home/lesson12
RUN git clone https://github.com/shephertz/App42PaaS-Java-MySQL-Sample.git
WORKDIR /home/lesson12/App42PaaS-Java-MySQL-Sample
RUN mvn package

